server:
  port: 80

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8080
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order-service/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**
